### PR TITLE
Input Mask component

### PR DESCRIPTION
**Pull request by patik**
Hides and shows sensitive data in input fields (e.g. passwords, SSNs). Ported from iflow.

Closes https://github.com/nyfrg/feta/issues/470.

### CODE REVIEW

**Comment by kodocode** [comment]
**Cursor Position when toggling between modes.**
Each browser seems to handle this differently, should we try and enforce a cursor position pattern when switching between modes?
- Firefox: Always positions cursor at end of input.
- Chrome: Remains at previous cursor position except when the last input action was a backspace in which case the cursor position is increased by 1 for each backspace used. 
- IE: Remains at previous cursor position even after using backspace. 

**Keyboard user accessibility**
Should the `show` / `hide` control be trigger-able by tabbing to the control and hitting enter?

**Comment by patik** [comment]
> Each browser seems to handle this differently, should we try and enforce a cursor position pattern when switching between modes?

I would say no. I think we should allow the browser's native behavior to shine through whenever possible. Users are expecting our pages to work the way other web sites do in the same browser.

> Should the `show` / `hide` control be trigger-able by tabbing to the control and hitting enter?

You could certainly make an argument for it. However if you're tabbing through the fields it would likely be annoying for most people to have that control "catch" the focus. Also, this control is meant primarily for situations where privacy isn't guaranteed (i.e. shoulder surfing) which is mostly applicable to smartphones with touch screens where tabbing isn't possible. I believe this is the decision we came to when we first developed it for iflow. You can check our analytics to make sure that assumption holds up.

**Comment by patik** [comment]
Adding:

- Ability to tab to the toggle and press Enter to activate it
- Unique ID for the button

**Comment by patik** [comment]
@kodocode Please re-review.

**Comment by kodocode** [comment]
Is there a reason for explicitly setting autocomplete[false] and spellcheck[true] attributes? This is the first time I've seen them used within the different projects.

**Comment by patik** [comment]
`autocomplete[false]` is because the unmasked field uses `type="text"` which means the browser will treat it like any other text field. We wouldn't want the browser to treat a password (which shouldn't match a dictionary word) or SSN (which may look like a phone number) as if it was normal input otherwise the user would have to be sure to dismiss the autocomplete UI.

`spellcheck[true]` is a bug in the sense that it should be set to `false`. Again, the same reasons listed above apply here. I'll fix it.

**Pull request merged**
